version: "3"

services:
  front:
    image: ull/front
    build:
      context: ./
      dockerfile: ./apps/ull/Dockerfile
    ports:
      - "3000:80"
  authentication:
    image: ull/authentication
    build:
      context: ./
      dockerfile: ./apps/authentication/Dockerfile
    env_file:
      - .env
    environment: #environment variables defined here override those from env_file. See : https://docs.docker.com/compose/environment-variables/#set-environment-variables-with-docker-compose-run
      - NODE_ENV=production
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - TYPEORM_AUTHENTICATION_URI=postgres://postgres@postgres-authentication:5432/authentication
    ports:
      - "3333:3333"
    networks:
      - services_database_postgres
  customer:
    image: ull/customer
    build:
      context: ./
      dockerfile: ./apps/customer/Dockerfile
    env_file:
      - .env
    environment: #environment variables defined here override those from env_file. See : https://docs.docker.com/compose/environment-variables/#set-environment-variables-with-docker-compose-run
      - NODE_ENV=production
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - TYPEORM_DISCOVERY_URI=postgres://postgres@postgres-customer:5432/customer
    ports:
      - "3335:3335"
    networks:
      - services_database_postgres
  discovery:
    image: ull/discovery
    build:
      context: ./
      dockerfile: ./apps/discovery/Dockerfile
    env_file:
      - .env
    environment: #environment variables defined here override those from env_file. See : https://docs.docker.com/compose/environment-variables/#set-environment-variables-with-docker-compose-run
      - NODE_ENV=production
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - TYPEORM_CUSTOMER_URI=postgres://postgres@postgres-discovery:5432/discovery
    ports:
      - "3337:3337"
    networks:
      - services_database_postgres
  reservation:
    image: ull/reservation
    build:
      context: ./
      dockerfile: ./apps/reservation/Dockerfile
    env_file:
      - .env
    environment: #environment variables defined here override those from env_file. See : https://docs.docker.com/compose/environment-variables/#set-environment-variables-with-docker-compose-run
      - NODE_ENV=production
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - TYPEORM_RESERVATION_URI=postgres://postgres@postgres-reservation:5432/reservation
    ports:
      - "3339:3339"
    networks:
      - services_database_postgres
  provider:
    image: ull/provider
    build:
      context: ./
      dockerfile: ./apps/provider/Dockerfile
    env_file:
      - .env
    environment: #environment variables defined here override those from env_file. See : https://docs.docker.com/compose/environment-variables/#set-environment-variables-with-docker-compose-run
      - NODE_ENV=production
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - TYPEORM_PROVIDER_URI=postgres://postgres@postgres-provider:5432/provider
    ports:
      - "3338:3338"
    networks:
      - services_database_postgres

networks:
  services_database_postgres:
    external: true
