version: "3"

services:
  authentication:
    image: ull/authentication
    build:
      context: ./
      dockerfile: ./apps/authentication/Dockerfile
    env_file:
      - .env
    environment: #environment variables defined here override those from env_file. See : https://docs.docker.com/compose/environment-variables/#set-environment-variables-with-docker-compose-run
      - NODE_ENV=production
      - RABBITMQ_URI=amqp://localhost:5672
      - TYPEORM_AUTHENTICATION_URI=postgres://postgres@localhost:5432/authentication
    ports:
      - "3333:3333"
  customer:
    image: ull/customer
    build:
      context: ./
      dockerfile: ./apps/customer/Dockerfile
    env_file:
      - .env
    environment: #environment variables defined here override those from env_file. See : https://docs.docker.com/compose/environment-variables/#set-environment-variables-with-docker-compose-run
      - NODE_ENV=production
      - RABBITMQ_URI=amqp://localhost:5672
      - TYPEORM_CUSTOMER_URI=postgres://postgres@localhost:5432/customer
    ports:
      - "3335:3335"
  provider:
    image: ull/provider
    build:
      context: ./
      dockerfile: ./apps/provider/Dockerfile
    env_file:
      - .env
    environment: #environment variables defined here override those from env_file. See : https://docs.docker.com/compose/environment-variables/#set-environment-variables-with-docker-compose-run
      - NODE_ENV=production
      - RABBITMQ_URI=amqp://localhost:5672
      - TYPEORM_PROVIDER_URI=postgres://postgres@localhost:5432/provider
    ports:
      - "3338:3338"
