version: '3'

services:
  authentication:
    image: ull/authentication
    build:
      context: ./
      dockerfile: ./apps/authentication/Dockerfile
    env_file:
      - .env
    environment: #environment variables defined here override those from env_file. See : https://docs.docker.com/compose/environment-variables/#set-environment-variables-with-docker-compose-run
      - NODE_ENV=production
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - TYPEORM_AUTHENTICATION_URI=postgres://postgres@postgres-authentication:5432/authentication
    depends_on:
      - rabbitmq
      - postgres-authentication
    ports:
      - "3333:3333"
  customer:
    image: ull/customer
    build:
      context: ./
      dockerfile: ./apps/customer/Dockerfile
    env_file:
      - .env
    environment: #environment variables defined here override those from env_file. See : https://docs.docker.com/compose/environment-variables/#set-environment-variables-with-docker-compose-run
      - NODE_ENV=production
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - TYPEORM_CUSTOMER_URI=postgres://postgres@postgres-customer:5432/customer
    depends_on:
      - rabbitmq
      - postgres-customer
    ports:
      - "3335:3335"
  postgres-authentication:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: authentication
      POSTGRES_HOST_AUTH_METHOD: trust
  postgres-reservation:
    image: postgres:14-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: reservation
      POSTGRES_HOST_AUTH_METHOD: trust
  postgres-provider:
    image: postgres:14-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: provider
      POSTGRES_HOST_AUTH_METHOD: trust
  postgres-customer:
    image: postgres:14-alpine
    ports:
      - "5436:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: customer
      POSTGRES_HOST_AUTH_METHOD: trust
  postgres-chat:
    image: postgres:14-alpine
    ports:
      - "5437:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: chat
      POSTGRES_HOST_AUTH_METHOD: trust
  postgres-discovery:
    image: postgres:14-alpine
    ports:
      - "5438:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: discovery
      POSTGRES_HOST_AUTH_METHOD: trust
  rabbitmq:
    image: rabbitmq:3.8.25-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge

